name: bangplasmartapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

# Add Package 
  splashscreen:
  font_awesome_flutter: ^8.5.0
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  http: 0.12.0+4
  intl: ^0.16.1
  image_picker: 0.6.3+4
  flutter_sparkline: "0.1.0"
  flutter_staggered_grid_view: "0.3.0"
  json_serializable: ^3.2.5
  smooth_star_rating: ^1.0.3
  # video_player: ^0.10.3
  multi_image_picker: ^4.6.1
  auto_size_text: 2.1.0
  path_provider: "^0.4.1"
  image: "^2.0.4"
  # shared_preferences: ^0.5.0
  carousel_slider: 1.4.1

  qr_flutter: ^3.0.1
  datetime_picker_formfield: ^1.0.0
  flutter_circular_chart: "0.1.0"
  charts_flutter : "0.9.0"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo-white-bangpla.jpg
    - assets/images/
    - assets/images/complain/
  fonts:
    - family: Maitree
      fonts:
        - asset: assets/fonts/Maitree/Maitree-Regular.ttf
        - asset: assets/fonts/Maitree/Maitree-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Maitree/Maitree-Light.ttf
          weight: 200
        - asset: assets/fonts/Maitree/Maitree-Medium.ttf
          weight: 400
        - asset: assets/fonts/Maitree/Maitree-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Maitree/Maitree-Bold.ttf
          weight: 700
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt/Prompt-Light.ttf
        - asset: assets/fonts/Prompt/Prompt-Regular.ttf
          weight: 400